// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.App.BackgroundTimer_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.GameConfig.Cleanup")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.GameConfig.TryRemoveProfile(System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindow.DeleteEnginePluginsOnExit(System.Diagnostics.Process)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindow.FillProcessList")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindow.FindAndInject")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindow.InjectIntoProcess(System.Nullable{System.UInt32},System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindow.MainWindow_IsVisibleChanged(System.Object,System.Windows.DependencyPropertyChangedEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindow.MainWindow_Loaded(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindow.MainWindow_Update~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindow.MonitorProcessExitAsync(System.Diagnostics.Process)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindow.OnStartTrace(System.Object,System.Management.EventArrivedEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindow.Update~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindowSettingsMenu.btnSelectVersion_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindowSettingsMenu.m_checkUpdatesBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindowSettingsMenu.SetCurrentRelease")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.MainWindowSettingsMenu.TabControl_SelectionChanged(System.Object,System.Windows.Controls.SelectionChangedEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.TrayContextMenu.Window_Deactivated(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.TrayContextMenu.Window_LostFocus(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.TrayContextMenu.Window_LostMouseCapture(System.Object,System.Windows.Input.MouseEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.TrayContextMenu.Window_MouseLeave(System.Object,System.Windows.Input.MouseEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.Updater.DownloadAndExtractAsync(UEVR.Utils.GitAPI.GitHubResponseObject,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.Updater.GetReleasesAsync~System.Threading.Tasks.Task{System.Collections.Generic.List{UEVR.Utils.GitAPI.GitHubResponseObject}}")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.Utils.CleanupScheduler.DeleteWhenUnlockedAsync(System.String,System.Threading.CancellationToken,System.Diagnostics.Process)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.Utils.GitAPI.CheckForUpdate(UEVR.Utils.GitAPI.UpdateClient,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.Utils.GitAPI.CheckForUpdateAsync(UEVR.Utils.GitAPI.UpdateClient,System.String,System.String,System.Nullable{System.DateTime})~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.Utils.GitAPI.DownloadSpecificRelease(UEVR.Utils.GitAPI.GitHubResponseObject,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.Utils.GitAPI.DownloadUpdateAsync(UEVR.Utils.GitAPI.UpdateClient,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.Utils.GitAPI.GetAllReleasesAsync(System.Net.Http.HttpClient,System.String,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{UEVR.Utils.GitAPI.GitHubResponseObject}}")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:UEVR.Utils.GitAPI.RunUpdateTasks(UEVR.Utils.GitAPI.UpdateClient,System.String,System.Nullable{System.DateTime},System.String,System.String,System.Boolean,System.Threading.Tasks.Task{System.Boolean})~System.Threading.Tasks.Task")]
